# Generated by Django 5.2.14 on 2026-05-10 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('wrong_password', 'Wrong password'), ('mfa_failed', 'MFA failed'), ('locked', 'Locked'), ('unknown_user', 'Unknown user'), ('inactive', 'Inactive account')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_attempted', 'created_at'], name='common_logi_email_a_8003c3_idx'), models.Index(fields=['ip_address', 'created_at'], name='common_logi_ip_addr_869b3f_idx')],
            },
        ),
    ]
